# Shared TypedDict structural definitions
import operator
from typing import List, Dict, Any, Optional, Annotated
from typing_extensions import TypedDict
from langchain_core.documents import Document

class AgentState(TypedDict):
    """
    Main state machine definition object utilized by the LangGraph runtime engine.
    Maintains user state boundaries, data chunks, and performance telemetry tracking.
    """
    # --- Context Identification Keys ---
    customer_id: str
    session_id: str
    question: str

    # --- Retrieval Output Storage ---
    # The graph nodes will update or overwrite this collection during execution steps
    documents: List[Document]

    # --- Customer Database Telemetry Profile ---
    plan_tier: str          # retail, business, enterprise, vip
    region: str             # e.g., US-NORTHEAST
    account_status: str     # active, suspended, terminated

    # --- Gemini Model Optimization Identifiers ---
    cache_name: Optional[str]  # Server-side hash key targeting Google's cloud context engine cache
    generation: str            # The output string response generated by Gemini

    # --- Telemetry & Audit Logs Reducer Channel ---
    # Annotating with operator.add enables safe appending of metrics objects
    # from any isolated graph node without losing historical trace tracking.
    metrics_log: Annotated[List[Dict[str, Any]], operator.add]
